env:
  browser: true
  es6: true
plugins:
  - prettier
extends:
  - eslint:recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  eqeqeq: error
  no-duplicate-imports: error
  no-unused-vars: [error, {vars: all, args: none}]
  no-var: error
  object-shorthand: [error, consistent]
  prefer-arrow-callback: error
  prefer-const: error
